name: ci_buildall

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_buildall.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libopenmpi-dev openmpi-bin

    - run: ctest -S setup.cmake -VV
      env:
        FC: gfortran
        CC: gcc
