name: ci_windows
env:
  CTEST_MUMPS_ARGS: "-Darith=d;-DCMAKE_INSTALL_PREFIX:PATH=~/mumps"
  CTEST_SITE: GitHub_Windows
  MUMPS_ROOT: ~/mumps


on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_windows.yml"


jobs:

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: CDash
      run: ctest -S ci.cmake -VV

    - run: cmake --install build
    - run: cmake -G "MinGW Makefiles" -S examples -B examples/build
    - run: cmake --build examples/build --parallel
    - run: ctest  -parallel 2 --output-on-failure
      working-directory: examples/build
